# Generated by Django 4.2 on 2023-05-21 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('main_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2023, 5, 20, 23, 50, 14, 428053))),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trasurer', models.ManyToManyField(blank=True, related_name='trasurer', to=settings.AUTH_USER_MODEL)),
                ('varients', models.ManyToManyField(related_name='varients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Varients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('chief', 'chief'), ('treasurer', 'treasurer'), ('varient', 'varient')], default='varient', max_length=9)),
                ('add_on', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clan', to='clan.clan')),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
