# Generated by Django 4.2 on 2023-06-08 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 9, 1, 57, 510923)),
        ),
        migrations.CreateModel(
            name='ClanSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saved_on', models.DateField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clan')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.varients')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='clan.varients')),
            ],
        ),
    ]
