# Generated by Django 4.2 on 2023-06-08 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_alter_clan_created_on_alter_clansaving_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 10, 55, 10, 20166)),
        ),
        migrations.AlterField(
            model_name='clansaving',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.varients'),
        ),
    ]
