# Generated by Django 4.2.2 on 2023-07-10 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0004_alter_clan_created_on_alter_clansaving_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 22, 15, 41, 796487)),
        ),
    ]
