# Generated by Django 4.2.3 on 2023-07-18 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0005_alter_clan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 12, 28, 5, 420145)),
        ),
    ]
