# Generated by Django 4.2.6 on 2023-10-14 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0008_alter_clan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 16, 5, 57, 377765)),
        ),
    ]
