# Generated by Django 5.1.3 on 2025-01-03 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0010_alter_clan_created_on_clanactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 17, 30, 33, 583378)),
        ),
    ]
