# Generated by Django 5.1.3 on 2025-01-03 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0011_clan_interest_alter_clan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 18, 15, 5, 237019)),
        ),
        migrations.AlterField(
            model_name='clan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='clan',
            name='main_balance',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
