# Generated by Django 5.1.3 on 2025-01-03 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0012_alter_clan_created_on_alter_clan_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='location',
            field=models.CharField(default='Not yet specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 18, 35, 35, 742173)),
        ),
    ]
