# Generated by Django 5.1.3 on 2025-01-09 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0013_clan_location_alter_clan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 3, 27, 48, 478135)),
        ),
        migrations.AlterField(
            model_name='clan',
            name='main_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
