# Generated by Django 5.1.3 on 2025-01-10 14:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0014_alter_clan_created_on_alter_clan_main_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 6, 21, 58, 268360)),
        ),
        migrations.AlterField(
            model_name='clan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ClanCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clan')),
                ('creadited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creadited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
