# Generated by Django 5.1.3 on 2025-01-12 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0015_alter_clan_created_on_alter_clan_interest_clancredit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clancredit',
            old_name='creadited_by',
            new_name='credited_by',
        ),
        migrations.AddField(
            model_name='clancredit',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='clancredit',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clancredit',
            name='percentage',
            field=models.CharField(choices=[('12', '1 Week'), ('20', '2 Weeks'), ('25', '25% 1Month'), ('30', '1 Month'), ('40', '8 Weeks'), ('50', '12 Weeks')], default='30', max_length=3),
        ),
        migrations.AddField(
            model_name='clancredit',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'pending'), ('denied', 'Denied'), ('payment', 'Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 1, 17, 29, 531285)),
        ),
    ]
