# Generated by Django 5.1.3 on 2025-01-12 09:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0016_rename_creadited_by_clancredit_credited_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clancredit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 1, 36, 1, 490813)),
        ),
        migrations.AlterField(
            model_name='clancredit',
            name='credited_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creadited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
