# Generated by Django 5.1.3 on 2025-01-12 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0018_clancredit_balance_alter_clan_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clancredit',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 2, 14, 29, 504757)),
        ),
    ]
