# Generated by Django 5.1.3 on 2025-01-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0019_clancredit_paid_alter_clan_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clancredit',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 2, 31, 25, 968016)),
        ),
    ]
