# Generated by Django 5.1.3 on 2025-01-13 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0020_remove_clancredit_approved_by_alter_clan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 22, 18, 50, 832435)),
        ),
        migrations.AlterField(
            model_name='clancredit',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
