# Generated by Django 5.1.3 on 2025-01-15 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0021_alter_clan_created_on_alter_clancredit_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 0, 55, 20, 247244)),
        ),
    ]
