# Generated by Django 5.1.3 on 2025-01-15 08:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0022_alter_clan_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 0, 56, 46, 768695)),
        ),
        migrations.AlterField(
            model_name='clancredit',
            name='credited_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
