# Generated by Django 5.1.3 on 2025-01-15 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0027_alter_clan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 1, 26, 10, 430137)),
        ),
    ]
