# Generated by Django 5.1.3 on 2025-01-16 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0030_clancredit_approved_by_alter_clan_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='money_in_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 2, 0, 228623)),
        ),
        migrations.AlterField(
            model_name='clanactivity',
            name='action',
            field=models.CharField(choices=[('CLAN_CREATED', 'Clan Created'), ('SAVINGS_ADDED', 'Savings Added'), ('VARIENT_ADDED', 'Varient Added'), ('CREDIT_APPROVED', 'CREDIT Approved')], max_length=20),
        ),
    ]
