# Generated by Django 5.1.3 on 2025-01-16 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0031_clan_money_in_credits_alter_clan_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 4, 45, 216982)),
        ),
    ]
