# Generated by Django 5.1.3 on 2025-01-16 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0032_clan_total_interest_alter_clan_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='revenue_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 7, 49, 335170)),
        ),
        migrations.AlterField(
            model_name='clan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clan',
            name='money_in_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
