# Generated by Django 5.1.3 on 2025-01-16 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0033_clan_revenue_share_alter_clan_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 28, 2, 266585)),
        ),
    ]
