# Generated by Django 5.1.3 on 2025-01-16 20:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0034_alter_clan_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 12, 36, 49, 298623)),
        ),
        migrations.CreateModel(
            name='ClanPaymentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clan.clancredit')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
