# Generated by Django 5.1.3 on 2025-02-03 11:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0038_alter_clan_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 3, 29, 5, 358124)),
        ),
        migrations.RenameModel(
            old_name='Varients',
            new_name='Varient',
        ),
        migrations.CreateModel(
            name='RevenueShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_out', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan.clan')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clancredit')),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.varient')),
            ],
        ),
    ]
