# Generated by Django 5.1.3 on 2025-02-03 13:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0039_alter_clan_created_on_rename_varients_varient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 5, 49, 52, 818235)),
        ),
        migrations.AlterField(
            model_name='clancredit',
            name='credited_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_by', to='clan.varient'),
        ),
        migrations.AlterField(
            model_name='revenueshare',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clan.clancredit'),
        ),
    ]
