# Generated by Django 5.1.3 on 2025-02-03 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0040_alter_clan_created_on_alter_clancredit_credited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='revenue_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 5, 58, 58, 598833)),
        ),
    ]
