# Generated by Django 5.1.3 on 2025-02-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0045_clansettings_is_active_clansettings_max_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clansettings',
            name='is_active',
        ),
        migrations.AddField(
            model_name='clansettings',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clansettings',
            name='max_members',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='clansettings',
            name='who_can_see_credits',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('staff', 'Trassurers and Chief')], default='everyone', max_length=25),
        ),
    ]
