# Generated by Django 5.1.6 on 2025-03-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0046_remove_clansettings_is_active_clansettings_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clancredit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clan.varient'),
        ),
    ]
