# Generated by Django 4.2.3 on 2023-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='revenue_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
