# Generated by Django 4.2 on 2023-05-18 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(choices=[('12', '1 Week'), ('20', '2 Weeks'), ('30', '1 Month'), ('40', '8 Weeks'), ('50', '16 Weeks')], default='30', max_length=3)),
                ('status', models.CharField(choices=[('pending_approval', 'pending'), ('denied', 'Denied'), ('payment', 'Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending_approval', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('approved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('witness_2_full_name', models.CharField(blank=True, max_length=30)),
                ('witness_2_NRC_number', models.CharField(blank=True, max_length=12)),
                ('witness_2_phone_number', models.CharField(blank=True, max_length=12)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='account.profile')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('witness_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.credit')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AproveCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='core.credit')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile')),
            ],
        ),
    ]
