# Generated by Django 4.2 on 2023-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='percentage',
            field=models.CharField(choices=[('12', '1 Week'), ('20', '2 Weeks'), ('30', '1 Month'), ('40', '8 Weeks'), ('50', '12 Weeks')], default='30', max_length=3),
        ),
    ]
