# Generated by Django 4.2.3 on 2023-08-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loanwitnessrevenue_delete_loanwitnessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanwitnessrevenue',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
